spring:
  application:
    name: order-service   # must match config-repo file
  profiles:
    active: dev                  # 👈 environment (dev / test / prod)
  config:
    import: optional:configserver:http://config-container:8888
